plugins:
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-md

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 50
