plugins:
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-rspec
  - rubocop-md

require:
  - rubocop-ai

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - '.gemini/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 200

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Naming/BlockForwarding:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

AI/AdverbSpam:
  Enabled: true