plugins:
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-rspec
  - rubocop-md

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 300


Layout/LineLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 300
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 100
