# frozen_string_literal: true

require 'rubocop'

module RuboCop
  module Cop
    module KeepAlive
      # This cop checks for comments that contain an excessive sequence of adverbs
      # or seemingly random words, which are often generated by malfunctioning AI
      # tools or LLM doc generators.
      #
      # @example
      #   # rubocop:disable KeepAlive/AdverbSpam - Architectural Limitation: This cop's own documentation must deliberately breach the rule to provide a negative example.
      #   # bad
      #   # @param c_m [String] securely accurately dynamically visually intuitively conditionally ...
      #   # rubocop:enable KeepAlive/AdverbSpam
      #
      #   # good
      #   # @param c_m [String] the properly formatted parameter
      class AdverbSpam < RuboCop::Cop::Base
        extend AutoCorrector

        MSG = 'Avoid AI-generated spam inside comments (excessive adverbs/meaningless words).'

        def on_new_investigation
          # Pattern to match sequences of 2 or more words ending in 'ly'
          # including optional spaces and punctuation in between (but NOT newlines).
          pattern = /(?:[ \t]*\b[a-zA-Z]+ly\b[ \t,.]*){2,}/i

          processed_source.comments.each do |comment|
            text = comment.text
            
            if text.match?(pattern)
              add_offense(comment) do |corrector|
                new_text = text.gsub(pattern, '').rstrip
                # Ensure the comment still starts with '#' if it got stripped entirely
                new_text = '#' if new_text.empty?
                corrector.replace(comment, new_text)
              end
            end
          end
        end
      end
    end
  end
end
