name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on semantic version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a GitHub Release
    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.2'
          bundler-cache: true

      - name: Set Release Version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/VERSION = '.*'/VERSION = '$TAG_VERSION'/" lib/keep_alive/version.rb

      - name: Build Gem
        run: gem build keep_alive.gemspec

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: "*.gem"
          generate_release_notes: true
